### ISSUE TITLE
 'PhenixPCast.h' file not found

### ISSUE THREAD

**Issue by SuvarnaRatna-DevRabbit** [PhenixRTS/PCastDemo#4]
Hi,

Thank you for the repository.

When I run the sample application in iOS getting error as " 'PhenixPCast.h' file not found".

Downloaded from git and then pod install.

Any help how to solve this issue.

Thank you.

**Comment by SuvarnaRatna-DevRabbit** [comment]
Hi , After running git-submodule-setup.sh file I am getting below error:

running git-submodule setup
Cloning into '/Users/devrabbit/PCastDemo/android/AndroidSDK'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:PhenixP2P/AndroidSDK.git' into submodule path '/Users/devrabbit/PCastDemo/android/AndroidSDK' failed
Failed to clone 'android/AndroidSDK'. Retry scheduled
Cloning into '/Users/devrabbit/PCastDemo/ios/iOSSDK'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:PhenixP2P/iOSSDK.git' into submodule path '/Users/devrabbit/PCastDemo/ios/iOSSDK' failed
Failed to clone 'ios/iOSSDK'. Retry scheduled
Cloning into '/Users/devrabbit/PCastDemo/android/AndroidSDK'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:PhenixP2P/AndroidSDK.git' into submodule path '/Users/devrabbit/PCastDemo/android/AndroidSDK' failed
Failed to clone 'android/AndroidSDK' a second time, aborting

Itseems unable to download sdk.

Please help me to solve this issue.

**Comment by andreas-schuler** [comment]
Hi Suvarna,

You may need to add your SSH key in your GitHub account here:
https://github.com/settings/keys

Please let me know if you are still getting permission issues after that. I have confirmed that your GitHub user 'SuvarnaRatna-DevRabbit' has read access to our mobile SDKs.

**Comment by andreas-schuler** [comment]
Did you run `pod install`? Also, make sure you are opening `PCastDemo.xcworkspace` afterwards.

**Comment by SuvarnaRatna-DevRabbit** [comment]
Hi Andreas,

Thank you very much for the help.I am able to download SDk now.

Below is the error I am getting now:

Use of unresolved identifier 'Reachability'
Use of unresolved identifier 'ReachabilityChangedNotification'

Can you please help me to solve this issue.

Regards,
Suvarna Ratna

**Comment by andreas-schuler** [comment]
To build for iOS you need to make sure are following all the steps outlined in the Readme.md:

1. One time only: Ensure Cocoapods is installed via gem: `sudo gem install cocoapods`
2. In the `ios/` directory: run `pod install` and then open **PCastDemo.xcworkspace** in Xcode

Can you confirm you ran those steps and are still having the issues you mentioned? If so, can you tell me when your environment looks like? What are your macOS and Xcode versions? Does `pod install` generate any errors?

**Comment by SuvarnaRatna-DevRabbit** [comment]
Hi team thanks for your support it is working fine.
Thanks a lot!!
